/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.schooldb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Academictestsubjects generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ACADEMICTESTSUBJECTS`")
@IdClass(AcademictestsubjectsId.class)
public class Academictestsubjects implements Serializable {

    private String academicyear;
    private Integer standardid;
    private Integer subjectid;
    private Integer testid;
    private String maxmarks;
    private Academicsubjects academicsubjects;
    private Testdetails testdetails;

    @Id
    @Column(name = "`ACADEMICYEAR`", nullable = false, length = 255)
    public String getAcademicyear() {
        return this.academicyear;
    }

    public void setAcademicyear(String academicyear) {
        this.academicyear = academicyear;
    }

    @Id
    @Column(name = "`STANDARDID`", nullable = false, scale = 0, precision = 10)
    public Integer getStandardid() {
        return this.standardid;
    }

    public void setStandardid(Integer standardid) {
        this.standardid = standardid;
    }

    @Id
    @Column(name = "`SUBJECTID`", nullable = false, scale = 0, precision = 10)
    public Integer getSubjectid() {
        return this.subjectid;
    }

    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    @Id
    @Column(name = "`TESTID`", nullable = false, scale = 0, precision = 10)
    public Integer getTestid() {
        return this.testid;
    }

    public void setTestid(Integer testid) {
        this.testid = testid;
    }

    @Column(name = "`MAXMARKS`", nullable = true, length = 255)
    public String getMaxmarks() {
        return this.maxmarks;
    }

    public void setMaxmarks(String maxmarks) {
        this.maxmarks = maxmarks;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumns(value = {
            @JoinColumn(name = "`ACADEMICYEAR`", referencedColumnName = "`ACADEMICYEAR`", insertable = false, updatable = false),
            @JoinColumn(name = "`STANDARDID`", referencedColumnName = "`STANDARDID`", insertable = false, updatable = false),
            @JoinColumn(name = "`SUBJECTID`", referencedColumnName = "`SUBJECTID`", insertable = false, updatable = false)},
        foreignKey = @ForeignKey(name = "`FKACADEMICTESTSUBJECTGRO6A`"))
    @Fetch(FetchMode.JOIN)
    public Academicsubjects getAcademicsubjects() {
        return this.academicsubjects;
    }

    public void setAcademicsubjects(Academicsubjects academicsubjects) {
        if(academicsubjects != null) {
            this.academicyear = academicsubjects.getAcademicyear();
            this.standardid = academicsubjects.getStandardid();
            this.subjectid = academicsubjects.getSubjectid();
        }

        this.academicsubjects = academicsubjects;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`TESTID`", referencedColumnName = "`TESTID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FKACADEMICTESTSUBJECTKGNBV`"))
    @Fetch(FetchMode.JOIN)
    public Testdetails getTestdetails() {
        return this.testdetails;
    }

    public void setTestdetails(Testdetails testdetails) {
        if(testdetails != null) {
            this.testid = testdetails.getTestid();
        }

        this.testdetails = testdetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Academictestsubjects)) return false;
        final Academictestsubjects academictestsubjects = (Academictestsubjects) o;
        return Objects.equals(getAcademicyear(), academictestsubjects.getAcademicyear()) &&
                Objects.equals(getStandardid(), academictestsubjects.getStandardid()) &&
                Objects.equals(getSubjectid(), academictestsubjects.getSubjectid()) &&
                Objects.equals(getTestid(), academictestsubjects.getTestid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAcademicyear(),
                getStandardid(),
                getSubjectid(),
                getTestid());
    }
}