/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.schooldb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Persons generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`PERSONS`")
@IdClass(PersonsId.class)
public class Persons implements Serializable {

    private Integer personId;
    private String firstname;
    private String lastname;
    private String address;
    private String city;
    private Date dateOfBirth;

    @Id
    @Column(name = "`PERSON_ID`", nullable = true, scale = 0, precision = 10)
    public Integer getPersonId() {
        return this.personId;
    }

    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    @Id
    @Column(name = "`FIRSTNAME`", nullable = true, length = 255)
    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Id
    @Column(name = "`LASTNAME`", nullable = true, length = 255)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Id
    @Column(name = "`ADDRESS`", nullable = true, length = 255)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Id
    @Column(name = "`CITY`", nullable = true, length = 255)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Id
    @Column(name = "`DATE_OF_BIRTH`", nullable = true)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Persons)) return false;
        final Persons persons = (Persons) o;
        return Objects.equals(getPersonId(), persons.getPersonId()) &&
                Objects.equals(getFirstname(), persons.getFirstname()) &&
                Objects.equals(getLastname(), persons.getLastname()) &&
                Objects.equals(getAddress(), persons.getAddress()) &&
                Objects.equals(getCity(), persons.getCity()) &&
                Objects.equals(getDateOfBirth(), persons.getDateOfBirth());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPersonId(),
                getFirstname(),
                getLastname(),
                getAddress(),
                getCity(),
                getDateOfBirth());
    }
}