/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.schooldb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Testconducted generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TESTCONDUCTED`")
@IdClass(TestconductedId.class)
public class Testconducted implements Serializable {

    private String academicyear;
    private Integer standardid;
    private Integer testconductedid;
    private int subjectid;
    private int testid;
    private Date testconductedon;
    private Academictestsubjects academictestsubjects;

    @Id
    @Column(name = "`ACADEMICYEAR`", nullable = false, length = 255)
    public String getAcademicyear() {
        return this.academicyear;
    }

    public void setAcademicyear(String academicyear) {
        this.academicyear = academicyear;
    }

    @Id
    @Column(name = "`STANDARDID`", nullable = false, scale = 0, precision = 10)
    public Integer getStandardid() {
        return this.standardid;
    }

    public void setStandardid(Integer standardid) {
        this.standardid = standardid;
    }

    @Id
    @Column(name = "`TESTCONDUCTEDID`", nullable = false, scale = 0, precision = 10)
    public Integer getTestconductedid() {
        return this.testconductedid;
    }

    public void setTestconductedid(Integer testconductedid) {
        this.testconductedid = testconductedid;
    }

    @Column(name = "`SUBJECTID`", nullable = false, scale = 0, precision = 10)
    public int getSubjectid() {
        return this.subjectid;
    }

    public void setSubjectid(int subjectid) {
        this.subjectid = subjectid;
    }

    @Column(name = "`TESTID`", nullable = false, scale = 0, precision = 10)
    public int getTestid() {
        return this.testid;
    }

    public void setTestid(int testid) {
        this.testid = testid;
    }

    @Column(name = "`TESTCONDUCTEDON`", nullable = true)
    public Date getTestconductedon() {
        return this.testconductedon;
    }

    public void setTestconductedon(Date testconductedon) {
        this.testconductedon = testconductedon;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumns(value = {
            @JoinColumn(name = "`ACADEMICYEAR`", referencedColumnName = "`ACADEMICYEAR`", insertable = false, updatable = false),
            @JoinColumn(name = "`STANDARDID`", referencedColumnName = "`STANDARDID`", insertable = false, updatable = false),
            @JoinColumn(name = "`TESTID`", referencedColumnName = "`TESTID`", insertable = false, updatable = false),
            @JoinColumn(name = "`SUBJECTID`", referencedColumnName = "`SUBJECTID`", insertable = false, updatable = false)},
        foreignKey = @ForeignKey(name = "`FKTESTCONDUCTEDTOACASSYPO`"))
    @Fetch(FetchMode.JOIN)
    public Academictestsubjects getAcademictestsubjects() {
        return this.academictestsubjects;
    }

    public void setAcademictestsubjects(Academictestsubjects academictestsubjects) {
        if(academictestsubjects != null) {
            this.academicyear = academictestsubjects.getAcademicyear();
            this.standardid = academictestsubjects.getStandardid();
            this.testid = academictestsubjects.getTestid();
            this.subjectid = academictestsubjects.getSubjectid();
        }

        this.academictestsubjects = academictestsubjects;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Testconducted)) return false;
        final Testconducted testconducted = (Testconducted) o;
        return Objects.equals(getAcademicyear(), testconducted.getAcademicyear()) &&
                Objects.equals(getStandardid(), testconducted.getStandardid()) &&
                Objects.equals(getTestconductedid(), testconducted.getTestconductedid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAcademicyear(),
                getStandardid(),
                getTestconductedid());
    }
}