/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.dbscenarios.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.sql.Date;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.angularjsdependencyinjection9_4.dbscenarios.TCrMany2one4;

/**
 * Service object for domain model class {@link TCrMany2one4}.
 */
public interface TCrMany2one4Service {

    /**
     * Creates a new TCrMany2one4. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on TCrMany2one4 if any.
     *
     * @param tcrMany2one4 Details of the TCrMany2one4 to be created; value cannot be null.
     * @return The newly created TCrMany2one4.
     */
    TCrMany2one4 create(@Valid TCrMany2one4 tcrMany2one4);


	/**
     * Returns TCrMany2one4 by given id if exists.
     *
     * @param tcrmany2one4Id The id of the TCrMany2one4 to get; value cannot be null.
     * @return TCrMany2one4 associated with the given tcrmany2one4Id.
	 * @throws EntityNotFoundException If no TCrMany2one4 is found.
     */
    TCrMany2one4 getById(Date tcrmany2one4Id);

    /**
     * Find and return the TCrMany2one4 by given id if exists, returns null otherwise.
     *
     * @param tcrmany2one4Id The id of the TCrMany2one4 to get; value cannot be null.
     * @return TCrMany2one4 associated with the given tcrmany2one4Id.
     */
    TCrMany2one4 findById(Date tcrmany2one4Id);

	/**
     * Find and return the list of TCrMany2one4s by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param tcrmany2one4Ids The id's of the TCrMany2one4 to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return TCrMany2one4s associated with the given tcrmany2one4Ids.
     */
    List<TCrMany2one4> findByMultipleIds(List<Date> tcrmany2one4Ids, boolean orderedReturn);


    /**
     * Updates the details of an existing TCrMany2one4. It replaces all fields of the existing TCrMany2one4 with the given tcrMany2one4.
     *
     * This method overrides the input field values using Server side or database managed properties defined on TCrMany2one4 if any.
     *
     * @param tcrMany2one4 The details of the TCrMany2one4 to be updated; value cannot be null.
     * @return The updated TCrMany2one4.
     * @throws EntityNotFoundException if no TCrMany2one4 is found with given input.
     */
    TCrMany2one4 update(@Valid TCrMany2one4 tcrMany2one4);

    /**
     * Deletes an existing TCrMany2one4 with the given id.
     *
     * @param tcrmany2one4Id The id of the TCrMany2one4 to be deleted; value cannot be null.
     * @return The deleted TCrMany2one4.
     * @throws EntityNotFoundException if no TCrMany2one4 found with the given id.
     */
    TCrMany2one4 delete(Date tcrmany2one4Id);

    /**
     * Deletes an existing TCrMany2one4 with the given object.
     *
     * @param tcrMany2one4 The instance of the TCrMany2one4 to be deleted; value cannot be null.
     */
    void delete(TCrMany2one4 tcrMany2one4);

    /**
     * Find all TCrMany2one4s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching TCrMany2one4s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<TCrMany2one4> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all TCrMany2one4s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching TCrMany2one4s.
     *
     * @see Pageable
     * @see Page
     */
    Page<TCrMany2one4> findAll(String query, Pageable pageable);

    /**
     * Exports all TCrMany2one4s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all TCrMany2one4s matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the TCrMany2one4s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the TCrMany2one4.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}