/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.dbscenarios1;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * CompositePk generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`CompositePK`")
@IdClass(CompositePkId.class)
public class CompositePk implements Serializable {

    private Integer intid;
    private Date dateid;
    private String stringcol;
    private Time timecol;
    private Boolean booleancol;

    @Id
    @Column(name = "`INTID`", nullable = false, scale = 0, precision = 10)
    public Integer getIntid() {
        return this.intid;
    }

    public void setIntid(Integer intid) {
        this.intid = intid;
    }

    @Id
    @Column(name = "`DATEID`", nullable = false)
    public Date getDateid() {
        return this.dateid;
    }

    public void setDateid(Date dateid) {
        this.dateid = dateid;
    }

    @Column(name = "`STRINGCOL`", nullable = true, length = 255)
    public String getStringcol() {
        return this.stringcol;
    }

    public void setStringcol(String stringcol) {
        this.stringcol = stringcol;
    }

    @Column(name = "`TIMECOL`", nullable = true)
    public Time getTimecol() {
        return this.timecol;
    }

    public void setTimecol(Time timecol) {
        this.timecol = timecol;
    }

    @Column(name = "`BOOLEANCOL`", nullable = true)
    public Boolean getBooleancol() {
        return this.booleancol;
    }

    public void setBooleancol(Boolean booleancol) {
        this.booleancol = booleancol;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CompositePk)) return false;
        final CompositePk compositePk = (CompositePk) o;
        return Objects.equals(getIntid(), compositePk.getIntid()) &&
                Objects.equals(getDateid(), compositePk.getDateid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIntid(),
                getDateid());
    }
}