/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.dbscenarios1;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * TCompositesMany2one generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`T_COMPOSITES_MANY2ONE`")
@IdClass(TCompositesMany2oneId.class)
public class TCompositesMany2one implements Serializable {

    private BigDecimal bigdecId;
    private Short shortId;
    private Short byteId;
    private String charId;
    private Date dateCol;
    private Boolean booleanCol;

    @Id
    @Column(name = "`BIGDEC ID`", nullable = false, scale = 15, precision = 35)
    public BigDecimal getBigdecId() {
        return this.bigdecId;
    }

    public void setBigdecId(BigDecimal bigdecId) {
        this.bigdecId = bigdecId;
    }

    @Id
    @Column(name = "`SHORT ID`", nullable = false, scale = 0, precision = 5)
    public Short getShortId() {
        return this.shortId;
    }

    public void setShortId(Short shortId) {
        this.shortId = shortId;
    }

    @Id
    @Column(name = "`BYTE ID`", nullable = false, scale = 0, precision = 3)
    public Short getByteId() {
        return this.byteId;
    }

    public void setByteId(Short byteId) {
        this.byteId = byteId;
    }

    @Id
    @Column(name = "`CHAR ID`", nullable = false, length = 1)
    public String getCharId() {
        return this.charId;
    }

    public void setCharId(String charId) {
        this.charId = charId;
    }

    @Column(name = "`DATE COL`", nullable = true)
    public Date getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(Date dateCol) {
        this.dateCol = dateCol;
    }

    @Column(name = "`BOOLEAN COL`", nullable = true)
    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TCompositesMany2one)) return false;
        final TCompositesMany2one tcompositesMany2one = (TCompositesMany2one) o;
        return Objects.equals(getBigdecId(), tcompositesMany2one.getBigdecId()) &&
                Objects.equals(getShortId(), tcompositesMany2one.getShortId()) &&
                Objects.equals(getByteId(), tcompositesMany2one.getByteId()) &&
                Objects.equals(getCharId(), tcompositesMany2one.getCharId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBigdecId(),
                getShortId(),
                getByteId(),
                getCharId());
    }
}