/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.schooldb.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.manager.ExportedFileManager;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.angularjsdependencyinjection9_4.schooldb.Academictestsubjects;
import com.angularjsdependencyinjection9_4.schooldb.AcademictestsubjectsId;
import com.angularjsdependencyinjection9_4.schooldb.Testconducted;
import com.angularjsdependencyinjection9_4.schooldb.service.AcademictestsubjectsService;


/**
 * Controller object for domain model class Academictestsubjects.
 * @see Academictestsubjects
 */
@RestController("SCHOOLDB.AcademictestsubjectsController")
@Api(value = "AcademictestsubjectsController", description = "Exposes APIs to work with Academictestsubjects resource.")
@RequestMapping("/SCHOOLDB/Academictestsubjects")
public class AcademictestsubjectsController {

    private static final Logger LOGGER = LoggerFactory.getLogger(AcademictestsubjectsController.class);

    @Autowired
	@Qualifier("SCHOOLDB.AcademictestsubjectsService")
	private AcademictestsubjectsService academictestsubjectsService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new Academictestsubjects instance.")
    @RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Academictestsubjects createAcademictestsubjects(@RequestBody Academictestsubjects academictestsubjects) {
		LOGGER.debug("Create Academictestsubjects with information: {}" , academictestsubjects);

		academictestsubjects = academictestsubjectsService.create(academictestsubjects);
		LOGGER.debug("Created Academictestsubjects with information: {}" , academictestsubjects);

	    return academictestsubjects;
	}

    @ApiOperation(value = "Returns the Academictestsubjects instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Academictestsubjects getAcademictestsubjects(@RequestParam("academicyear") String academicyear, @RequestParam("standardid") Integer standardid, @RequestParam("subjectid") Integer subjectid, @RequestParam("testid") Integer testid) {

        AcademictestsubjectsId academictestsubjectsId = new AcademictestsubjectsId();
        academictestsubjectsId.setAcademicyear(academicyear);
        academictestsubjectsId.setStandardid(standardid);
        academictestsubjectsId.setSubjectid(subjectid);
        academictestsubjectsId.setTestid(testid);

        LOGGER.debug("Getting Academictestsubjects with id: {}" , academictestsubjectsId);
        Academictestsubjects academictestsubjects = academictestsubjectsService.getById(academictestsubjectsId);
        LOGGER.debug("Academictestsubjects details with id: {}" , academictestsubjects);

        return academictestsubjects;
    }



    @ApiOperation(value = "Updates the Academictestsubjects instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Academictestsubjects editAcademictestsubjects(@RequestParam("academicyear") String academicyear, @RequestParam("standardid") Integer standardid, @RequestParam("subjectid") Integer subjectid, @RequestParam("testid") Integer testid, @RequestBody Academictestsubjects academictestsubjects) {

        academictestsubjects.setAcademicyear(academicyear);
        academictestsubjects.setStandardid(standardid);
        academictestsubjects.setSubjectid(subjectid);
        academictestsubjects.setTestid(testid);

        LOGGER.debug("Academictestsubjects details with id is updated with: {}" , academictestsubjects);

        return academictestsubjectsService.update(academictestsubjects);
    }


    @ApiOperation(value = "Deletes the Academictestsubjects instance associated with the given composite-id.")
    @RequestMapping(value = "/composite-id", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteAcademictestsubjects(@RequestParam("academicyear") String academicyear, @RequestParam("standardid") Integer standardid, @RequestParam("subjectid") Integer subjectid, @RequestParam("testid") Integer testid) {

        AcademictestsubjectsId academictestsubjectsId = new AcademictestsubjectsId();
        academictestsubjectsId.setAcademicyear(academicyear);
        academictestsubjectsId.setStandardid(standardid);
        academictestsubjectsId.setSubjectid(subjectid);
        academictestsubjectsId.setTestid(testid);

        LOGGER.debug("Deleting Academictestsubjects with id: {}" , academictestsubjectsId);
        Academictestsubjects academictestsubjects = academictestsubjectsService.delete(academictestsubjectsId);

        return academictestsubjects != null;
    }


    /**
     * @deprecated Use {@link #findAcademictestsubjects(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Academictestsubjects instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Academictestsubjects> searchAcademictestsubjectsByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Academictestsubjects list by query filter:{}", (Object) queryFilters);
        return academictestsubjectsService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Academictestsubjects instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Academictestsubjects> findAcademictestsubjects(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Academictestsubjects list by filter:", query);
        return academictestsubjectsService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Academictestsubjects instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @RequestMapping(value="/filter", method = RequestMethod.POST, consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Academictestsubjects> filterAcademictestsubjects(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Academictestsubjects list by filter", query);
        return academictestsubjectsService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
    @RequestMapping(value = "/export/{exportType}", method = {RequestMethod.GET,  RequestMethod.POST}, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportAcademictestsubjects(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return academictestsubjectsService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @RequestMapping(value = "/export", method = {RequestMethod.POST}, consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportAcademictestsubjectsAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = Academictestsubjects.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> academictestsubjectsService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of Academictestsubjects instances matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
	@RequestMapping(value = "/count", method = {RequestMethod.GET, RequestMethod.POST})
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countAcademictestsubjects( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Academictestsubjects");
		return academictestsubjectsService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@RequestMapping(value = "/aggregations", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getAcademictestsubjectsAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return academictestsubjectsService.getAggregatedValues(aggregationInfo, pageable);
    }

    @RequestMapping(value="/composite-id/testconducteds", method=RequestMethod.GET)
    @ApiOperation(value = "Gets the testconducteds instance associated with the given composite-id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Testconducted> findAssociatedTestconducteds(@RequestParam("academicyear") String academicyear, @RequestParam("standardid") Integer standardid, @RequestParam("subjectid") Integer subjectid, @RequestParam("testid") Integer testid, Pageable pageable) {

        LOGGER.debug("Fetching all associated testconducteds");
        return academictestsubjectsService.findAssociatedTestconducteds(academicyear, standardid, subjectid, testid, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service AcademictestsubjectsService instance
	 */
	protected void setAcademictestsubjectsService(AcademictestsubjectsService service) {
		this.academictestsubjectsService = service;
	}

}