/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * CharColumnCheckTable generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`CHAR COLUMN CHECK-TABLE`")
@IdClass(CharColumnCheckTableId.class)
public class CharColumnCheckTable implements Serializable {

    private Integer serialId;
    private String charCol;

    @Id
    @Column(name = "`SERIAL ID`", nullable = false, scale = 0, precision = 10)
    public Integer getSerialId() {
        return this.serialId;
    }

    public void setSerialId(Integer serialId) {
        this.serialId = serialId;
    }

    @Id
    @Column(name = "`CHAR COL`", nullable = false, length = 1)
    public String getCharCol() {
        return this.charCol;
    }

    public void setCharCol(String charCol) {
        this.charCol = charCol;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CharColumnCheckTable)) return false;
        final CharColumnCheckTable charColumnCheckTable = (CharColumnCheckTable) o;
        return Objects.equals(getSerialId(), charColumnCheckTable.getSerialId()) &&
                Objects.equals(getCharCol(), charColumnCheckTable.getCharCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSerialId(),
                getCharCol());
    }
}