/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Table448 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLE448`", uniqueConstraints = {
            @UniqueConstraint(name = "`UK_TABLE448_COLUMN5_COLUMN6`", columnNames = {"`COLUMN5`", "`COLUMN6`"})})
public class Table448 implements Serializable {

    private Integer id;
    private String column6;
    private String column7;
    private String column3;
    private Boolean column4;
    private String column8;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] column5;

    @Id
    @SequenceGenerator(name = "generator", sequenceName = "`TABLE448_ID_seq`" , allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`COLUMN6`", nullable = true, length = 255)
    public String getColumn6() {
        return this.column6;
    }

    public void setColumn6(String column6) {
        this.column6 = column6;
    }

    @Column(name = "`COLUMN7`", nullable = true, length = 255)
    public String getColumn7() {
        return this.column7;
    }

    public void setColumn7(String column7) {
        this.column7 = column7;
    }

    @Column(name = "`COLUMN3`", nullable = true, length = 1)
    public String getColumn3() {
        return this.column3;
    }

    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    @Column(name = "`COLUMN4`", nullable = true)
    public Boolean getColumn4() {
        return this.column4;
    }

    public void setColumn4(Boolean column4) {
        this.column4 = column4;
    }

    @Column(name = "`COLUMN8`", nullable = true, length = 255)
    public String getColumn8() {
        return this.column8;
    }

    public void setColumn8(String column8) {
        this.column8 = column8;
    }

    @Column(name = "`COLUMN5`", nullable = false)
    public byte[] getColumn5() {
        return this.column5;
    }

    public void setColumn5(byte[] column5) {
        this.column5 = column5;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table448)) return false;
        final Table448 table448 = (Table448) o;
        return Objects.equals(getId(), table448.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}