/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

public class TCrMany2one3Id implements Serializable {

    private BigDecimal doubleCol;
    private Short shortId;
    private String stringCol;
    private BigDecimal bigdecCol;

    public BigDecimal getDoubleCol() {
        return this.doubleCol;
    }

    public void setDoubleCol(BigDecimal doubleCol) {
        this.doubleCol = doubleCol;
    }

    public Short getShortId() {
        return this.shortId;
    }

    public void setShortId(Short shortId) {
        this.shortId = shortId;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    public BigDecimal getBigdecCol() {
        return this.bigdecCol;
    }

    public void setBigdecCol(BigDecimal bigdecCol) {
        this.bigdecCol = bigdecCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TCrMany2one3)) return false;
        final TCrMany2one3 tcrMany2one3 = (TCrMany2one3) o;
        return Objects.equals(getDoubleCol(), tcrMany2one3.getDoubleCol()) &&
                Objects.equals(getShortId(), tcrMany2one3.getShortId()) &&
                Objects.equals(getStringCol(), tcrMany2one3.getStringCol()) &&
                Objects.equals(getBigdecCol(), tcrMany2one3.getBigdecCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDoubleCol(),
                getShortId(),
                getStringCol(),
                getBigdecCol());
    }
}