/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

public class TCrOne2one1Id implements Serializable {

    private BigDecimal intId;
    private String stringCol;
    private Integer bigdecCol;

    public BigDecimal getIntId() {
        return this.intId;
    }

    public void setIntId(BigDecimal intId) {
        this.intId = intId;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    public Integer getBigdecCol() {
        return this.bigdecCol;
    }

    public void setBigdecCol(Integer bigdecCol) {
        this.bigdecCol = bigdecCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TCrOne2one1)) return false;
        final TCrOne2one1 tcrOne2one1 = (TCrOne2one1) o;
        return Objects.equals(getIntId(), tcrOne2one1.getIntId()) &&
                Objects.equals(getStringCol(), tcrOne2one1.getStringCol()) &&
                Objects.equals(getBigdecCol(), tcrOne2one1.getBigdecCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIntId(),
                getStringCol(),
                getBigdecCol());
    }
}