/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Time;
import java.util.Objects;

public class VirtualMany2one1Id implements Serializable {

    private String characterType;
    private Time timeType;
    private Boolean booleanType;

    public String getCharacterType() {
        return this.characterType;
    }

    public void setCharacterType(String characterType) {
        this.characterType = characterType;
    }

    public Time getTimeType() {
        return this.timeType;
    }

    public void setTimeType(Time timeType) {
        this.timeType = timeType;
    }

    public Boolean getBooleanType() {
        return this.booleanType;
    }

    public void setBooleanType(Boolean booleanType) {
        this.booleanType = booleanType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof VirtualMany2one1)) return false;
        final VirtualMany2one1 virtualMany2one1 = (VirtualMany2one1) o;
        return Objects.equals(getCharacterType(), virtualMany2one1.getCharacterType()) &&
                Objects.equals(getTimeType(), virtualMany2one1.getTimeType()) &&
                Objects.equals(getBooleanType(), virtualMany2one1.getBooleanType());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCharacterType(),
                getTimeType(),
                getBooleanType());
    }
}