/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.schooldb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.angularjsdependencyinjection9_4.schooldb.Personbackup;
import com.angularjsdependencyinjection9_4.schooldb.PersonbackupId;


/**
 * ServiceImpl object for domain model class Personbackup.
 *
 * @see Personbackup
 */
@Service("SCHOOLDB.PersonbackupService")
@Validated
public class PersonbackupServiceImpl implements PersonbackupService {

    private static final Logger LOGGER = LoggerFactory.getLogger(PersonbackupServiceImpl.class);


    @Autowired
    @Qualifier("SCHOOLDB.PersonbackupDao")
    private WMGenericDao<Personbackup, PersonbackupId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Personbackup, PersonbackupId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "SCHOOLDBTransactionManager")
    @Override
    public Personbackup create(Personbackup personbackup) {
        LOGGER.debug("Creating a new Personbackup with information: {}", personbackup);

        Personbackup personbackupCreated = this.wmGenericDao.create(personbackup);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(personbackupCreated);
    }

    @Transactional(readOnly = true, value = "SCHOOLDBTransactionManager")
    @Override
    public Personbackup getById(PersonbackupId personbackupId) {
        LOGGER.debug("Finding Personbackup by id: {}", personbackupId);
        return this.wmGenericDao.findById(personbackupId);
    }

    @Transactional(readOnly = true, value = "SCHOOLDBTransactionManager")
    @Override
    public Personbackup findById(PersonbackupId personbackupId) {
        LOGGER.debug("Finding Personbackup by id: {}", personbackupId);
        try {
            return this.wmGenericDao.findById(personbackupId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Personbackup found with id: {}", personbackupId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "SCHOOLDBTransactionManager")
    @Override
    public List<Personbackup> findByMultipleIds(List<PersonbackupId> personbackupIds, boolean orderedReturn) {
        LOGGER.debug("Finding Personbackups by ids: {}", personbackupIds);

        return this.wmGenericDao.findByMultipleIds(personbackupIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "SCHOOLDBTransactionManager")
    @Override
    public Personbackup update(Personbackup personbackup) {
        LOGGER.debug("Updating Personbackup with information: {}", personbackup);

        this.wmGenericDao.update(personbackup);
        this.wmGenericDao.refresh(personbackup);

        return personbackup;
    }

    @Transactional(value = "SCHOOLDBTransactionManager")
    @Override
    public Personbackup delete(PersonbackupId personbackupId) {
        LOGGER.debug("Deleting Personbackup with id: {}", personbackupId);
        Personbackup deleted = this.wmGenericDao.findById(personbackupId);
        if (deleted == null) {
            LOGGER.debug("No Personbackup found with id: {}", personbackupId);
            throw new EntityNotFoundException(String.valueOf(personbackupId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "SCHOOLDBTransactionManager")
    @Override
    public void delete(Personbackup personbackup) {
        LOGGER.debug("Deleting Personbackup with {}", personbackup);
        this.wmGenericDao.delete(personbackup);
    }

    @Transactional(readOnly = true, value = "SCHOOLDBTransactionManager")
    @Override
    public Page<Personbackup> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Personbackups");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "SCHOOLDBTransactionManager")
    @Override
    public Page<Personbackup> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Personbackups");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "SCHOOLDBTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service SCHOOLDB for table Personbackup to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "SCHOOLDBTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service SCHOOLDB for table Personbackup to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "SCHOOLDBTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "SCHOOLDBTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}