/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.angularjsdependencyinjection9_4.dbscenarios1.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.angularjsdependencyinjection9_4.dbscenarios1.PersonBackup;

/**
 * Service object for domain model class {@link PersonBackup}.
 */
public interface PersonBackupService {

    /**
     * Creates a new PersonBackup. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on PersonBackup if any.
     *
     * @param personBackup Details of the PersonBackup to be created; value cannot be null.
     * @return The newly created PersonBackup.
     */
    PersonBackup create(@Valid PersonBackup personBackup);


	/**
     * Returns PersonBackup by given id if exists.
     *
     * @param personbackupId The id of the PersonBackup to get; value cannot be null.
     * @return PersonBackup associated with the given personbackupId.
	 * @throws EntityNotFoundException If no PersonBackup is found.
     */
    PersonBackup getById(Integer personbackupId);

    /**
     * Find and return the PersonBackup by given id if exists, returns null otherwise.
     *
     * @param personbackupId The id of the PersonBackup to get; value cannot be null.
     * @return PersonBackup associated with the given personbackupId.
     */
    PersonBackup findById(Integer personbackupId);

	/**
     * Find and return the list of PersonBackups by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param personbackupIds The id's of the PersonBackup to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return PersonBackups associated with the given personbackupIds.
     */
    List<PersonBackup> findByMultipleIds(List<Integer> personbackupIds, boolean orderedReturn);


    /**
     * Updates the details of an existing PersonBackup. It replaces all fields of the existing PersonBackup with the given personBackup.
     *
     * This method overrides the input field values using Server side or database managed properties defined on PersonBackup if any.
     *
     * @param personBackup The details of the PersonBackup to be updated; value cannot be null.
     * @return The updated PersonBackup.
     * @throws EntityNotFoundException if no PersonBackup is found with given input.
     */
    PersonBackup update(@Valid PersonBackup personBackup);

    /**
     * Deletes an existing PersonBackup with the given id.
     *
     * @param personbackupId The id of the PersonBackup to be deleted; value cannot be null.
     * @return The deleted PersonBackup.
     * @throws EntityNotFoundException if no PersonBackup found with the given id.
     */
    PersonBackup delete(Integer personbackupId);

    /**
     * Deletes an existing PersonBackup with the given object.
     *
     * @param personBackup The instance of the PersonBackup to be deleted; value cannot be null.
     */
    void delete(PersonBackup personBackup);

    /**
     * Find all PersonBackups matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching PersonBackups.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<PersonBackup> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all PersonBackups matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching PersonBackups.
     *
     * @see Pageable
     * @see Page
     */
    Page<PersonBackup> findAll(String query, Pageable pageable);

    /**
     * Exports all PersonBackups matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all PersonBackups matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the PersonBackups in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the PersonBackup.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}